import {enc,now,b64,un64,uuid,validateConfig,encrypt,decrypt,deviceState,applyReceipt,vaultKey} from './protocol.js';
const $=id=>document.getElementById(id), date=t=>new Date(t*1000).toLocaleString('zh-CN');
let c, vault, salt, items=[], heartbeat=null, health={status:false,receipts:false}, running=false, controllers=[], saveChain=Promise.resolve(), syncBusy=false, probeId=null, probeStarted=0;
const notice=s=>{$('notice').textContent=s;};
const packet=(type,extra={})=>({v:1,id:uuid(),device_id:c.device_id,type,sent_at:now(),...extra});
async function persist(){const snapshot=JSON.stringify({config:c,items});saveChain=saveChain.catch(()=>{}).then(async()=>{const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},vault,enc.encode(snapshot));localStorage.setItem('mr-vault',JSON.stringify({v:1,salt:b64(salt),iv:b64(iv),data:b64(data)}));});return saveChain;}
function render(){const matching=c.mode!=='ondemand'||(heartbeat&&heartbeat.request_id===probeId);const state=deviceState(matching?heartbeat:null,health.status);$('state').textContent={online:'刚刚检测在线',offline:'电脑离线 / 心跳超时',unknown:'连接状态未知'}[state];$('dot').className='dot '+state;$('heartbeat').textContent=heartbeat?'最近心跳：'+date(heartbeat.sent_at):'尚未取得有效心跳';$('messages').replaceChildren();for(const item of [...items].reverse()){const card=document.createElement('article');card.className='message-card';const meta=document.createElement('div');meta.className='meta';meta.textContent=date(item.sent_at);const text=document.createElement('p');text.textContent=item.text;const status=document.createElement('div');status.className='receipt';status.textContent=({pending:'等待送达',unknown:'发送结果未知，等待核对',failed:'发送失败',delivered:'已送达，等待阅读',read:'已确认阅读'})[item.status]||'等待送达';if(item.delivery_mode)status.textContent+=' · '+(item.delivery_mode==='offline'?'离线补收':'实时送达');if(item.event_at)status.textContent+=' · '+date(item.event_at);if(!['read','delivered'].includes(item.status)&&now()-item.sent_at>43200)status.textContent='已超出12小时补收窗口，无法保证送达，请联系对方';card.append(meta,text,status);if(!['read','delivered'].includes(item.status)&&now()-item.sent_at<43200){const btn=document.createElement('button');btn.className='secondary';btn.textContent='核对并重试同一消息';btn.onclick=()=>retry(item,btn);card.append(btn);}$('messages').append(card);}if(!items.length)$('messages').textContent='还没有待确认消息。';}
function headers(){return c.token?{Authorization:'Bearer '+c.token}:{};}
async function request(url,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(url,{...options,headers:{...headers(),...options.headers},signal:controller.signal,cache:'no-store',referrerPolicy:'no-referrer'});if(!r.ok){const e=Error(r.status===429?'服务限流，请稍后再试；消息状态已保留':'服务器请求失败 HTTP '+r.status);e.status=r.status;throw e;}return r;}finally{clearTimeout(timer);}}
async function publish(p){const wire=await encrypt(c,p,'messages');const r=await request(`${c.server}/${c.topics.messages}`,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:wire});const reply=await r.json();if(reply.event!=='message'||!reply.id)throw Error('服务器未返回有效发送确认');return reply;}
async function consume(e,channel){if(e.event!=='message')return;let p;try{p=await decrypt(c,e.message,channel);}catch{return;}if(channel==='status'){if(!heartbeat||p.sent_at>heartbeat.sent_at)heartbeat=p;}else{let changed=false;for(const m of items)changed=applyReceipt(m,p)||changed;if(changed)await persist();}render();}
async function poll(channel,since='12h'){const r=await request(`${c.server}/${c.topics[channel]}/json?poll=1&since=${encodeURIComponent(since)}`);if(r.headers.get('X-Messages-Truncated')==='1')notice('服务器缓存被截断，较早消息可能缺失。');const body=await r.text();for(const line of body.split('\n'))if(line.trim()){try{await consume(JSON.parse(line),channel);}catch{}}health[channel]=true;render();}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function listen(channel){let delay=1000;while(running){const controller=new AbortController();controllers.push(controller);let timer;try{const r=await fetch(`${c.server}/${c.topics[channel]}/json?since=12h`,{headers:headers(),signal:controller.signal,cache:'no-store',referrerPolicy:'no-referrer'});if(!r.ok)throw Error('监听失败 HTTP '+r.status);if(!r.body||!r.body.getReader)throw Error('浏览器不支持流式读取');health[channel]=true;delay=1000;render();const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';const watchdog=()=>{clearTimeout(timer);timer=setTimeout(()=>controller.abort(),65000);};watchdog();while(running){const {value,done}=await reader.read();if(done)break;watchdog();buffer+=decoder.decode(value,{stream:true});if(buffer.length>1048576)throw Error('服务器响应过大');let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);if(line.trim()){try{await consume(JSON.parse(line),channel);}catch{}}}}}catch{health[channel]=false;if(running)notice('监听暂时中断，正在恢复；设备状态可能未知。');}finally{clearTimeout(timer);controllers=controllers.filter(x=>x!==controller);controller.abort();health[channel]=false;render();}if(running){await sleep(delay+Math.random()*500);delay=Math.min(delay*2,60000);}}}
async function sync(){if(syncBusy)return;syncBusy=true;$('refresh').disabled=true;try{await Promise.all([poll('status'),poll('receipts')]);const query=packet('sync',{ids:items.filter(m=>m.status!=='read').slice(-20).map(m=>m.id)});probeId=query.id;probeStarted=now();render();await publish(query);setTimeout(()=>{if(running&&(!heartbeat||heartbeat.request_id!==probeId)&&now()-probeStarted>=19)notice('检测超时，电脑可能离线，也可能网络异常或服务限流；状态未知。');},20000);notice('已查询缓存并请求电脑刷新。未收到新心跳时保持未知，不能据此确认电脑已关机。');}catch(e){health.status=false;notice(e.message);}finally{syncBusy=false;render();setTimeout(()=>$('refresh').disabled=false,60000);}}
async function retry(item,btn){btn.disabled=true;try{await poll('receipts');if(['read','delivered'].includes(item.status))return;const r=await request(`${c.server}/${c.topics.messages}/json?poll=1&since=12h`);let found=false;for(const line of (await r.text()).split('\n')){try{const e=JSON.parse(line),p=await decrypt(c,e.message,'messages');if(p.id===item.id)found=true;}catch{}}if(found){item.status='pending';notice('服务器缓存中已有此消息，继续等待电脑送达。');}else{await publish({v:1,id:item.id,device_id:c.device_id,type:'message',sent_at:item.sent_at,text:item.text});item.status='pending';notice('已重发同一消息 ID，电脑会去重。');}}catch(e){notice(e.message);if(!['read','delivered'].includes(item.status))item.status='unknown';}finally{await persist();render();}}
$('unlock').onclick=async()=>{try{if(!window.isSecureContext||!crypto.subtle)throw Error('请通过 HTTPS 网站打开，当前环境不支持安全加密。');const password=$('password').value,raw=$('pair').value.trim();if(raw){if(password.length<4)throw Error('首次本机口令至少4个字符');if(localStorage.getItem('mr-vault')&&!confirm('重新配对会覆盖此浏览器的旧配对和待确认状态，确定继续？'))return;c=validateConfig(JSON.parse(raw));c.token=$('token').value.trim();items=[];salt=crypto.getRandomValues(new Uint8Array(16));vault=await vaultKey(password,salt);await persist();}else{const saved=JSON.parse(localStorage.getItem('mr-vault')||'null');if(!saved)throw Error('请先输入配对信息');salt=un64(saved.salt);vault=await vaultKey(password,salt);const data=await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(saved.iv)},vault,un64(saved.data));const stored=JSON.parse(new TextDecoder().decode(data));c=validateConfig(stored.config);items=stored.items;}$('password').value='';$('pair').value='';$('token').value='';$('gate').hidden=true;$('app').hidden=false;$('mode').textContent=c.mode==='ondemand'?'按需检测：打开网页或点击按钮检测；平时不发送心跳。检测结果60秒后变为未知。':c.mode==='free'?'旧免费模式：后台每10分钟心跳。':'标准模式：每15秒心跳，超过60秒无新心跳判为离线；手机网络异常时为未知。';items=items.filter(m=>m.status!=='read'||now()-(m.event_at||m.sent_at)<86400);running=true;notice('正在恢复设备状态和回执…');render();listen('status');listen('receipts');await sync();}catch(e){notice(e.name==='OperationError'?'解锁失败，请检查口令。':e.message);}};
$('send').onclick=async()=>{let item;try{const text=$('message').value.trim();if(!text)throw Error('请输入消息');if(enc.encode(text).length>2000)throw Error('消息不得超过2000个UTF-8字节（约666个汉字）');if(items.filter(m=>m.status!=='read').length>=100)throw Error('待确认消息已达100条，请先处理已有消息');$('send').disabled=true;item={id:uuid(),sent_at:Math.max(now(),...items.map(m=>m.sent_at+.001)),text,status:'unknown'};items.push(item);await persist();render();await publish({v:1,id:item.id,device_id:c.device_id,type:'message',sent_at:item.sent_at,text});if(!['delivered','read'].includes(item.status))item.status='pending';$('message').value='';$('count').textContent='0 / 2000 字节';notice('服务器已接受，等待电脑送达回执。');}catch(e){if(item&&!['read','delivered'].includes(item.status))item.status=e.status?'failed':'unknown';notice(e.message+'；若发送结果未知，请先核对再重试。');}finally{if(item){try{await persist();}catch{notice('浏览器存储失败，请保持页面打开并检查存储空间。');}}render();$('send').disabled=false;}};
$('message').oninput=()=>{$('count').textContent=enc.encode($('message').value).length+' / 2000 字节';};
$('refresh').onclick=sync;
$('lock').onclick=async()=>{running=false;controllers.forEach(x=>x.abort());await persist();location.reload();};
setInterval(()=>{if(running)render();},1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&running)sync();});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});



