export const enc = new TextEncoder();
export const now = () => Date.now()/1000;
export const b64 = a => btoa(String.fromCharCode(...new Uint8Array(a)));
export const un64 = s => Uint8Array.from(atob(s), c=>c.charCodeAt(0));
export function uuid(){if(crypto.randomUUID)return crypto.randomUUID();const a=crypto.getRandomValues(new Uint8Array(16));a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;const s=Array.from(a,x=>x.toString(16).padStart(2,'0')).join('');return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`;}
export const validId = x => typeof x==='string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(x);
export function validateConfig(c){const u=new URL(c.server);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||!validId(c.device_id)||un64(c.key).length!==32||!['ondemand','free','standard'].includes(c.mode))throw Error('配对信息格式无效');if(new Set(Object.values(c.topics)).size!==3)throw Error('主题必须不同');for(const k of ['messages','status','receipts'])if(!/^[a-zA-Z0-9_-]{16,64}$/.test(c.topics[k]))throw Error('无效主题');c.server=c.server.replace(/\/$/,'');return c;}
export async function keyFor(c){return crypto.subtle.importKey('raw',un64(c.key),'AES-GCM',false,['encrypt','decrypt']);}
export async function encrypt(c,p,channel){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(`mr-v1:${channel}:${c.device_id}`)},await keyFor(c),enc.encode(JSON.stringify(p)));const wire=JSON.stringify({v:1,iv:b64(iv),data:b64(data)});if(enc.encode(wire).length>4096)throw Error('消息太长');return wire;}
export async function decrypt(c,wire,channel,t=now()){if(enc.encode(wire).length>4096)throw Error('消息过大');const e=JSON.parse(wire);if(e.v!==1)throw Error('版本错误');const data=await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(e.iv),additionalData:enc.encode(`mr-v1:${channel}:${c.device_id}`)},await keyFor(c),un64(e.data));const p=JSON.parse(new TextDecoder().decode(data));if(p.v!==1||p.device_id!==c.device_id||!validId(p.id)||!Number.isFinite(p.sent_at)||p.sent_at<t-43200||p.sent_at>t+30)throw Error('无效或过期消息');if(channel==='status'){if(p.type!=='heartbeat'||!['connected','reconnecting'].includes(p.state)||!['ondemand','free','standard'].includes(p.mode))throw Error('无效心跳');}else if(channel==='receipts'){if(!['delivered','read'].includes(p.type)||!validId(p.message_id)||!Number.isFinite(p.event_at)||p.event_at>t+30||!['live','offline'].includes(p.delivery_mode))throw Error('无效回执');}return p;}
export function deviceState(heartbeat,healthy,t=now()){if(!healthy||!heartbeat)return 'unknown';const age=t-heartbeat.sent_at;if(age< -30)return 'unknown';if(age<=60&&heartbeat.state==='connected')return 'online';if(heartbeat.mode==='standard'&&age>60)return 'offline';return 'unknown';}
export function applyReceipt(message,p){if(message.id!==p.message_id||p.event_at<message.sent_at-30)return false;if(message.status==='read'&&p.type==='delivered')return false;message.status=p.type;message.event_at=p.event_at;message.delivery_mode=p.delivery_mode;if(p.type==='read')message.text='（已阅读，正文已从本机移除）';return true;}
export async function vaultKey(password,salt){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}


